------------------------------------------------------------------------
-- Data initial importation FBBS and species functionnal indicators
------------------------------------------------------------------------

DROP table if exists point;
CREATE TABLE point  
	(pk_point varchar(100) primary key,
	 id_carre varchar(100) NOT NULL,
         commune varchar(50),
         site varchar,
         insee varchar(6),
         departement varchar(3),
         num_point varchar(2),
         nom_point varchar(2),
         altitude double precision,
         longitude_wgs84 double precision,
         latitude_wgs84 double precision,
	 longitude_wgs84_sd double precision,
         latitude_wgs84_sd double precision,
         db varchar(15) NOT NULL,
	 date_export varchar(10) NOT NULL);


DROP table if exists carre;
CREATE TABLE carre
       (pk_carre varchar(100) primary key,
       nom_carre varchar(100),
       nom_carre_fnat varchar(100),
       commune varchar(50),
       site varchar,
       etude varchar(25),
       etude_detail varchar(30),
       insee varchar(5),   
       departement varchar(3),
       altitude_median double precision,
       aire int,
       perimetre int,
       latitude_median_wgs84 double precision,
       longitude_median_wgs84 double precision,
       latitude_grid_wgs84 double precision,
       longitude_grid_wgs84 double precision,
       db varchar(15) NOT NULL,
       date_export varchar(10) NOT NULL);




DROP table if exists inventaire;
CREATE TABLE inventaire
       (pk_inventaire varchar(100) primary key,
       id_raw_inventaire varchar(100),
       etude varchar(25),
       etude_detail varchar(30),
       id_carre varchar(100) NOT NULL,
       id_point varchar(100) NOT NULL,
       num_point varchar(2),
       annee int  NOT NULL,
       date varchar(10) NOT NULL,
       jour_julien int NOT NULL,
       datetime varchar(25),
       passage_observateur int,
       passage_stoc int,
       periode_passage varchar(10),
       repetition_passage int,
       inc_passage int,
       nombre_passage_anne int,
       nombre_passage_stoc_annee int,
       info_passage_an varchar(10),
       info_pasage varchar(25),
       nb_sem_entre_passage double precision,
       info_temps_entre_passage varchar(10),
       heure_debut varchar(5),
       heure_fin varchar(5),
       duree_minute int,
       diff_sunrise_h double precision,
       diff_daw_h double precision,
       info_heure_debut varchar(10),
       nuage int,
       pluie int,
       vent int,
       visibilite int,
       neige int,
       observateur varchar(50),
       email varchar(50),
       db varchar(15) NOT NULL,
       date_export varchar(10) NOT NULL,
       version varchar(20) NOT NULL);


DROP table if exists observation;
CREATE TABLE observation
       (pk_observation varchar(100) primary key,
        id_raw_observation varchar(100),
        id_inventaire varchar(100) NOT NULL,
        id_point varchar(100)  NOT NULL,
        id_carre varchar(100) NOT NULL,
        num_point int,
        date varchar(10) NOT NULL,
        annee int NOT NULL,
        classe varchar(15),
	id_data varchar(100),
        espece varchar(9) NOT NULL,
        code_sp varchar(6) NOT NULL,
        distance_contact varchar(8)NOT NULL,
        abondance int NOT NULL,
        nuage int,
        pluie int,
        vent int,
        visibilite int,
        neige int,
	p_habitat varchar(3),
        p_milieu varchar(1),
       	p_type int,
       	p_cat1 int,
       	p_cat2 int,
	p_sous_cat1 int,
	p_sous_cat2 int,
       	s_habitat varchar(3),
       	s_milieu varchar(1),
       	s_type int,
       	s_cat1 int,
       	s_cat2 int,
	s_sous_cat1 int,
	s_sous_cat2 int,
 	db varchar(15) NOT NULL,
	date_export varchar(10) NOT NULL);


DROP table if exists habitat;
create TABLE habitat
       (pk_habitat varchar(100) primary key,
       id_point varchar(100)  NOT NULL,
       date varchar(10) NOT NULL,
       annee int NOT NULL,
       p_habitat_sug varchar(3),
       p_habitat varchar(3),
       p_habitat_consistent boolean,
       p_milieu varchar(1),
       p_type int,
       p_cat1 int,
       p_cat2 int,
       p_sous_cat1 int,
       p_sous_cat2 int,
       s_habitat_sug varchar(3),
       s_habitat varchar(3),
       s_habitat_consistent boolean,
       s_milieu varchar(1),
       s_type int,
       s_cat1 int,
       s_cat2 int,
       s_sous_cat1 int,
       s_sous_cat2 int,
       time_last_declaration_sug_j int,
       db varchar(15) NOT NULL,
       date_export varchar(10) NOT NULL);

