------------------------------------------------------------------------
-- Data initial importation FBBS and species functionnal indicators
------------------------------------------------------------------------

DROP table if exists point;
CREATE TABLE point  
	(pk_point varchar(100) primary key,
	 id_carre varchar(100) NOT NULL,
         commune varchar(50),
         site varchar,
         insee varchar(6),
         departement varchar(3),
         num_point varchar(2),
         nom_point varchar(2),
         altitude double precision,
         longitude_wgs84 double precision,
         latitude_wgs84 double precision,
	 longitude_wgs84_sd double precision,
         latitude_wgs84_sd double precision,
	 nb_sp int,
	 nb_sp_mean double precision,
	 abondance_mean double precision,
         db varchar(15) NOT NULL,
	 date_export varchar(10) NOT NULL);


DROP table if exists carre;
CREATE TABLE carre
       (pk_carre varchar(100) primary key,
       nom_carre varchar(100),
       commune varchar(50),
       site varchar,
       etude varchar(25),
       etude_detail varchar(30),
       insee varchar(5),   
       departement varchar(3),
       altitude_median double precision,
       nb_point int,
       aire double precision,
       perimetre double precision,
       latitude_median_wgs84 double precision,
       longitude_median_wgs84 double precision,
       latitude_grid_wgs84 double precision,
       longitude_grid_wgs84 double precision,
       first_year int,
       last_year int,
       duration int,
       nb_year int,
       nb_sp int,
       nb_sp_mean double precision,
       abondance_point_mean double precision,
       db varchar(15) NOT NULL,
       date_export varchar(10) NOT NULL);




DROP table if exists inventaire;
CREATE TABLE inventaire
       (pk_inventaire varchar(100) primary key,
       id_raw_inventaire varchar(100),
       etude varchar(25),
       etude_detail varchar(30),
       id_carre varchar(100) NOT NULL,
       id_point varchar(100) NOT NULL,
       num_point varchar(2),
       annee int  NOT NULL,
       date varchar(10) NOT NULL,
       jour_julien int NOT NULL,
       datetime varchar(25),
       passage_observateur int,
       passage_stoc int,
       periode_passage varchar(10),
       repetition_passage int,
       inc_passage int,
       nombre_passage_anne int,
       nombre_passage_stoc_annee int,
       info_passage_an varchar(10),
       info_passage varchar(25),
       nb_sem_entre_passage double precision,
       info_temps_entre_passage varchar(10),
       heure_debut varchar(5),
       heure_fin varchar(5),
       duree_minute int,
       diff_sunrise_h double precision,
       diff_daw_h double precision,
       info_heure_debut varchar(10),
       nuage int,
       pluie int,
       vent int,
       visibilite int,
       neige int,
       observateur varchar(100),
       email varchar(100),
       db varchar(15) NOT NULL,
       date_export varchar(10) NOT NULL,
       version varchar(20) NOT NULL);


DROP table if exists observation;
CREATE TABLE observation
       (pk_observation varchar(100) primary key,
        id_raw_observation varchar(100),
        id_inventaire varchar(100) NOT NULL,
        id_point varchar(100)  NOT NULL,
        id_carre varchar(100) NOT NULL,
        num_point int,
        date varchar(10) NOT NULL,
        annee int NOT NULL,
        classe varchar(15),
	id_data varchar(100),
        espece varchar(9) NOT NULL,
        code_sp varchar(6) NOT NULL,
        distance_contact varchar(8)NOT NULL,
        abondance int NOT NULL,
        nuage int,
        pluie int,
        vent int,
        visibilite int,
        neige int,
	p_habitat varchar(3),
        p_milieu varchar(1),
       	p_type int,
       	p_cat1 int,
       	p_cat2 int,
	p_sous_cat1 int,
	p_sous_cat2 int,
       	s_habitat varchar(3),
       	s_milieu varchar(1),
       	s_type int,
       	s_cat1 int,
       	s_cat2 int,
	s_sous_cat1 int,
	s_sous_cat2 int,
 	db varchar(15) NOT NULL,
	date_export varchar(10) NOT NULL);

DROP table if exists seuil_obs;
CREATE TABLE seuil_obs
       (code_sp varchar(6) NOT NULL,
       seuil_all_tukey_outlier double precision,
       seuil_all_tukey_farout double precision,
       seuil_inf_tukey_outlier double precision,
       seuil_inf_tukey_farout double precision,
       seuil_200_tukey_outlier double precision,
       seuil_200_tukey_farout double precision,
       seuil_100_tukey_outlier double precision,
       seuil_100_tukey_farout double precision);


DROP table if exists habitat;
create TABLE habitat
       (pk_habitat varchar(100) primary key,
       id_point varchar(100)  NOT NULL,
       date varchar(10) NOT NULL,
       annee int NOT NULL,
       nb_description int,
       habitat_sug varchar(7),
       habitat varchar(7),
       habitat_collapse varchar(100),
       habitat_consistent boolean,
       time_last_declaration_sug_j int,
       p_habitat_sug varchar(3),
       p_habitat varchar(3),
       p_habitat_collapse varchar(100),
       p_milieu_sug varchar(1),
       p_milieu varchar(1),
       p_type int,
       p_cat1 int,
       p_cat2 int,
       p_sous_cat1 int,
       p_sous_cat2 int,
       s_habitat_sug varchar(3),
       s_habitat varchar(3),
       s_habitat_collapse varchar(100),
       s_milieu_sug varchar(1),
       s_milieu varchar(1),
       s_type int,
       s_cat1 int,
       s_cat2 int,
       s_sous_cat1 int,
       s_sous_cat2 int,
       db varchar(15) NOT NULL,
       date_export varchar(10) NOT NULL);




DROP table if exists point_annee;
create TABLE point_annee
       (pk_point_annee varchar(100) primary key,
       id_point varchar(100) NOT NULL,
       id_carre varchar(100) NOT NULL,
       annee int NOT NULL,
       qualite_inventaire_stoc double precision,
       nombre_passage_stoc_annee int,
       info_passage_an varchar(10),
       habitat_collapse varchar(100),
       p_habitat_collapse varchar(100),
       s_habitat_collapse varchar(100),
       time_declaration_sug_j double precision,
       foret_p boolean,
       foret_ps boolean,
       ouvert_p boolean,
       ouvert_ps boolean,
       agri_p boolean,
       agri_ps boolean,
       urbain_p boolean,
       urbain_ps boolean,
       info_heure_debut_pass1 varchar(10),
       nb_description_pass1 int,
       habitat_sug_pass1 varchar(7),
       habitat_collapse_pass1 varchar(100),
       habitat_consistent_pass1 boolean,
       p_habitat_sug_pass1 varchar(3),
       p_habitat_pass1 varchar(3),
       p_milieu_sug_pass1 varchar(1),
       s_habitat_sug_pass1 varchar(3),
       s_habitat_pass1 varchar(3),
       s_milieu_sug_pass1 varchar(3),
       info_heure_debut_pass2 varchar(10),
       nb_description_pass2 int,
       habitat_sug_pass2 varchar(7),
       habitat_collapse_pass2 varchar(100),
       habitat_consistent_pass2 boolean,
       p_habitat_sug_pass2 varchar(3),
       p_habitat_pass2 varchar(3),
       p_milieu_sug_pass2 varchar(1),
       s_habitat_sug_pass2 varchar(3),
       s_habitat_pass2 varchar(3),
       s_milieu_sug_pass2 varchar(3));





DROP table if exists carre_annee;
create TABLE carre_annee
       (pk_carre_annee varchar(100) primary key,
       id_carre varchar(100) NOT NULL,
       annee int NOT NULL,
       qualite_inventaire_stoc double precision,
       nombre_passage_stoc_annee int,
       info_passage_an varchar(10),
       nbp_foret_p int,
       nbp_foret_ps int,
       nbp_ouvert_p int,
       nbp_ouvert_ps int,
       nbp_agri_p int,
       nbp_agri_ps int,
       nbp_urbain_p int,
       nbp_urbain_ps int,
       foret_p boolean,
       foret_ps boolean,
       ouvert_p boolean,
       ouvert_ps boolean,
       agri_p boolean,
       agri_ps boolean,
       urbain_p boolean,
       urbain_ps boolean);








DROP table if exists all_data;
create TABLE all_data
       (id_raw_observation varchar,
       id_raw_inventaire varchar,
       etude varchar(25),
       site varchar,
       insee varchar(5),
       commune varchar(50),
       id_carre varchar(100),
       date varchar(10),
       heure varchar(5),
       heure_fin varchar(5),
       observateur varchar(100),
       num_point varchar(2),
       altitude int,
       espece varchar(9),
       classe varchar(15),
       abondance int,
       distance_contact varchar(8),
       longitude_wgs84 double precision,
       latitude_wgs84 double precision,
       nuage int,
       pluie int,
       vent int,
       visibilite int,
       neige int,
       p_milieu varchar(1),
       p_type int,
       p_cat1 int,
       p_cat2 int,
       p_sous_cat1 int,
       p_sous_cat2 int,
       s_milieu varchar(1),
       s_type int,
       s_cat1 int,
       s_cat2 int,
       s_sous_cat1 int,
       s_sous_cat2 int,
       date_export varchar(10),
       departement varchar(3),
       etude_detail varchar(30),
       nom_carre varchar(100),
       point varchar,
       id_point varchar(100),
       jour_julien int,
       annee int,
       id_inventaire  varchar(100),
       duree_minute int,
       id_data varchar(100),
       inventaire_inc int,
       id_observation varchar(100),
       db varchar(15),
       info_passage varchar(25),
       passage_stoc int,
       passage_observateur int,
       email varchar(100),
       code_sp varchar(6),
       keep boolean);

